#!/bin/bash
# Run this once from the "potfolio website" folder to copy all project images into /assets/
# Usage: bash setup-assets.sh

SITE_DIR="$(cd "$(dirname "$0")" && pwd)"
ASSETS="$SITE_DIR/assets"
DL="/Users/abeekuacquah/Downloads"

mkdir -p "$ASSETS"

echo "Copying The Last Portrait..."
cp "$DL/aged/aged1.jpg"    "$ASSETS/"
cp "$DL/aged/aged1-2.jpg"  "$ASSETS/"
cp "$DL/aged/aged1-3.jpg"  "$ASSETS/"
cp "$DL/aged/aged1-5.jpg"  "$ASSETS/"
cp "$DL/aged/aged1-6.jpg"  "$ASSETS/"
cp "$DL/aged/aged1-7.jpg"  "$ASSETS/"
cp "$DL/aged/aged1-8.jpg"  "$ASSETS/"
cp "$DL/aged/aged1-9.jpg"  "$ASSETS/"
cp "$DL/aged/aged1-10.jpg" "$ASSETS/"
cp "$DL/aged/aged1-11.jpg" "$ASSETS/"

echo "Copying Love Your Problem (renaming files with spaces)..."
cp "$DL/LOVE YOUR PROBLEM/ace-35.jpg"    "$ASSETS/"
cp "$DL/LOVE YOUR PROBLEM/ace-25.jpg"    "$ASSETS/"
cp "$DL/LOVE YOUR PROBLEM/ace-10 (2).jpg" "$ASSETS/ace-10(2).jpg"
cp "$DL/LOVE YOUR PROBLEM/ace-14 (1).jpg" "$ASSETS/ace-14(1).jpg"
cp "$DL/LOVE YOUR PROBLEM/ace-19 (1).jpg" "$ASSETS/ace-19(1).jpg"
cp "$DL/LOVE YOUR PROBLEM/ace-24 (1).jpg" "$ASSETS/ace-24(1).jpg"

echo "Copying OHNI Foundation..."
cp "$DL/OHNI/OHNI-00318.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-00392.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-06789.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-06812.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-06964.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-07581.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-07900.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-08188.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-08697.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-08787.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-08821.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-08864.jpg" "$ASSETS/"
cp "$DL/OHNI/OHNI-09369.jpg" "$ASSETS/"

echo "Copying Touching Grass..."
cp "$DL/TOUCHING GRASS/NAT003.jpeg" "$ASSETS/"
cp "$DL/TOUCHING GRASS/NAT023.jpeg" "$ASSETS/"
cp "$DL/TOUCHING GRASS/NAT028.jpeg" "$ASSETS/"
cp "$DL/TOUCHING GRASS/NAT082.jpeg" "$ASSETS/"
cp "$DL/TOUCHING GRASS/NAT117.jpeg" "$ASSETS/"
cp "$DL/TOUCHING GRASS/NAT298.jpeg" "$ASSETS/"

echo "Copying UNICEF WASH..."
cp "$DL/UNICEF WASH/UNIC144.jpeg" "$ASSETS/"
cp "$DL/UNICEF WASH/UNIC154.jpeg" "$ASSETS/"
cp "$DL/UNICEF WASH/UNIC164.jpeg" "$ASSETS/"
cp "$DL/UNICEF WASH/UNIC830.jpeg" "$ASSETS/"
cp "$DL/UNICEF WASH/UNIC893.jpeg" "$ASSETS/"
cp "$DL/UNICEF WASH/UNIC899.jpeg" "$ASSETS/"
cp "$DL/UNICEF WASH/UNIC912.jpeg" "$ASSETS/"

echo ""
echo "Done. $(ls "$ASSETS" | wc -l | tr -d ' ') files now in /assets/"
